---
- name: Ensure httpd rpm package is installed
  yum:
    name: 'httpd'
    # state: present, in order not to upgrade any package to an untested version
    state: present
  become: yes
  tags: httpd-service

- name: Ensure required httpd modules are installed
  yum:
    name:
    - mod_ssl
    - mod_php
    - mod_security
    - mod_security_crs
    # state: present, in order not to upgrade any package to an untested version
    state: present
  become: yes
  notify: Restart httpd
  tags: httpd-service
